import { Dimensions, Platform, StyleSheet } from "react-native";
import { ThemeColors } from "../../providers/ThemeProvider";
const { width } = Dimensions.get("window");
const CARD_MARGIN = 10;
const CARD_SIZE = (width - CARD_MARGIN * 3) / 2; // two columns with margins

export const makePlaylistManagementStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingBottom: Platform.OS === "ios" ? 34 : 16,
    },
    headerRow: {
      paddingHorizontal: 20,
      // Increase top padding so header sits lower
      paddingTop: Platform.OS === "ios" ? 32 : 22,
      paddingBottom: 20,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      borderBottomWidth: 1,
      borderBottomColor: colors.inactiveBar,
      marginBottom: 8,
    },
    title: {
      fontSize: 26,
      fontWeight: "700",
      color: colors.primaryText,
      letterSpacing: -0.5,
      marginLeft: 12,
    },
    // Grid / card styles
    listContent: {
      paddingHorizontal: CARD_MARGIN,
      paddingTop: 12,
    },
    columnWrapper: {
      justifyContent: "space-between",
    },
    card: {
      width: CARD_SIZE,
      marginBottom: CARD_MARGIN,
      alignItems: "center",
      backgroundColor: "transparent",
    },
    imageContainer: {
      width: CARD_SIZE - 14,
      height: CARD_SIZE - 14,
      borderRadius: 12,
      overflow: Platform.OS === "android" ? "hidden" : "visible",
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 4,
    },
    image: {
      width: "100%",
      height: "100%",
      resizeMode: "cover",
      borderRadius: 12,
      backgroundColor: colors.inactiveBar,
    },
    cardInfo: {
      marginTop: 8,
      alignItems: "center",
      width: "100%",
      paddingHorizontal: 2,
    },
    itemTitle: {
      color: colors.primaryText,
      fontSize: 13,
      fontWeight: "700",
      marginBottom: 2,
      letterSpacing: -0.2,
      textAlign: "center",
    },
    itemDesc: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: "500",
      textAlign: "center",
    },
    itemTrackCount: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "500",
      marginTop: 4,
    },
    actionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    actionButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      minWidth: 50,
      alignItems: "center",
      justifyContent: "center",
    },
    editActionButton: {
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    deleteActionButton: {
      borderWidth: 1.5,
      borderColor: colors.destructive || "#c0392b",
    },
    actionButtonText: {
      fontWeight: "700",
      fontSize: 13,
      letterSpacing: 0.1,
    },
    createButton: {
      backgroundColor: colors.accent,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 10,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    createButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
    },
    emptyStateIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
      overflow: "hidden",
    },
    emptyStateTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.primaryText,
      marginBottom: 12,
      letterSpacing: -0.3,
      textAlign: "center",
    },
    emptyStateText: {
      color: colors.secondaryText,
      marginBottom: 20,
      marginHorizontal: 12,
      fontSize: 16,
      textAlign: "center",
      lineHeight: 22,
      fontWeight: "500",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: colors.background,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 30,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
    modalHeader: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.primaryText,
      marginBottom: 20,
      letterSpacing: -0.3,
    },
    input: {
      borderWidth: 1.5,
      borderColor: colors.inactiveBar,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 12,
      color: colors.primaryText,
      marginBottom: 14,
      fontSize: 16,
      fontWeight: "500",
      backgroundColor: colors.cardBg || colors.surface,
    },
    inputPlaceholder: {
      color: colors.secondaryText,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
      marginTop: 20,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: colors.inactiveBar,
    },
    cancelButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
    },
    cancelButtonText: {
      color: colors.secondaryText,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.1,
    },
    saveButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.1,
    },
    fab: {
      position: "absolute",
      right: 18,
      bottom: Platform.OS === "ios" ? 34 : 18,
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 6,
    },
  });
