import { Dimensions, Platform, StyleSheet } from "react-native";
import { ThemeColors } from "../../providers/ThemeProvider";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const makePlaylistManagementStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 24,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === "ios" ? 16 : 12,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.inactiveBar,
    },
    title: {
      fontSize: 28,
      fontWeight: "800",
      color: colors.primaryText,
      letterSpacing: -0.5,
    },
    listItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginHorizontal: 16,
      marginVertical: 8,
      backgroundColor: colors.cardBg || colors.surface,
      borderRadius: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
    },
    thumb: {
      width: 64,
      height: 64,
      borderRadius: 10,
      marginRight: 14,
      backgroundColor: colors.inactiveBar,
    },
    listInner: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
    },
    itemLeft: {
      flexDirection: "row",
      alignItems: "center",
    },
    itemTitle: {
      color: colors.primaryText,
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 4,
      letterSpacing: -0.2,
    },
    itemDesc: {
      color: colors.secondaryText,
      fontSize: 13,
      fontWeight: "500",
      marginBottom: 4,
    },
    itemTrackCount: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "500",
    },
    actionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    actionButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      minWidth: 50,
      alignItems: "center",
      justifyContent: "center",
    },
    editActionButton: {
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    deleteActionButton: {
      borderWidth: 1.5,
      borderColor: colors.destructive || "#c0392b",
    },
    actionButtonText: {
      fontWeight: "700",
      fontSize: 13,
      letterSpacing: 0.1,
    },
    createButton: {
      backgroundColor: colors.accent,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 10,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    createButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
    },
    emptyStateIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    emptyStateText: {
      color: colors.secondaryText,
      marginBottom: 20,
      marginHorizontal: 12,
      fontSize: 16,
      textAlign: "center",
      lineHeight: 22,
      fontWeight: "500",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: colors.background,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 30,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
    modalHeader: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.primaryText,
      marginBottom: 20,
      letterSpacing: -0.3,
    },
    input: {
      borderWidth: 1.5,
      borderColor: colors.inactiveBar,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 12,
      color: colors.primaryText,
      marginBottom: 14,
      fontSize: 16,
      fontWeight: "500",
      backgroundColor: colors.cardBg || colors.surface,
    },
    inputPlaceholder: {
      color: colors.secondaryText,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
      marginTop: 20,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: colors.inactiveBar,
    },
    cancelButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
    },
    cancelButtonText: {
      color: colors.secondaryText,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.1,
    },
    saveButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.1,
    },
  });
