import { Dimensions, Platform, StyleSheet } from "react-native";
import { ThemeColors } from "../../providers/ThemeProvider";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const COVER_SIZE = Math.min(SCREEN_WIDTH * 0.7, 220);

export const makePlaylistDetailStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      paddingHorizontal: 20,
      paddingTop: Platform.OS === "ios" ? 16 : 16,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.inactiveBar,
    },
    backButton: {
      padding: 8,
      borderRadius: 8,
    },
    headerActionButton: {
      padding: 8,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: "auto",
    },
    headerTitle: {
      color: colors.primaryText,
      fontSize: 20,
      fontWeight: "700",
      letterSpacing: -0.3,
      marginLeft: 12,
    },
    coverWrap: {
      alignItems: "center",
      paddingTop: 18,
      paddingBottom: 18,
    },
    cover: {
      width: COVER_SIZE,
      height: COVER_SIZE,
      borderRadius: 14,
      marginBottom: 16,
      backgroundColor: colors.inactiveBar,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 6,
    },
    coverTitle: {
      color: colors.primaryText,
      fontSize: 18,
      fontWeight: "700",
      textAlign: "center",
      paddingHorizontal: 16,
      letterSpacing: -0.3,
    },
    statsRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 14,
      paddingHorizontal: 16,
      width: "100%",
    },
    statChip: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 14,
      backgroundColor: colors.cardBg || colors.surface,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      alignItems: "center",
    },
    statValue: {
      color: colors.primaryText,
      fontSize: 16,
      letterSpacing: -0.2,
    },
    statLabel: {
      color: colors.secondaryText,
      fontSize: 12,
      marginTop: 2,
    },
    playControlsRow: {
      flexDirection: "row",
      marginTop: 12,
      gap: 12,
      paddingHorizontal: 16,
      width: "100%",
    },
    controlButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      minHeight: 44,
    },
    playAllButton: {
      flex: 1,
      backgroundColor: colors.accent,
      paddingVertical: 10,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    playAllText: {
      color: "#fff",
      fontWeight: "700",
    },
    shuffleButton: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
      backgroundColor: colors.cardBg || colors.surface,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      alignItems: "center",
      justifyContent: "center",
    },
    shuffleText: {
      color: colors.primaryText,
      fontWeight: "700",
    },
    playbackRow: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 12,
      marginTop: 12,
      paddingHorizontal: 16,
      width: "100%",
    },
    iconControlButton: {
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.cardBg || colors.surface,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
    },
    filterRow: {
      marginTop: 12,
      paddingHorizontal: 16,
      width: "100%",
      gap: 10,
    },
    filterToggleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginTop: 10,
      paddingHorizontal: 16,
      width: "100%",
    },
    filterToggle: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      flex: 1,
      minHeight: 42,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      backgroundColor: colors.cardBg || colors.surface,
    },
    filterToggleActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    filterToggleText: {
      color: colors.primaryText,
      fontSize: 13,
    },
    filterToggleTextActive: {
      color: "#fff",
    },
    filterClearButton: {
      minHeight: 42,
      paddingHorizontal: 14,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      backgroundColor: colors.cardBg || colors.surface,
    },
    filterClearText: {
      color: colors.secondaryText,
      fontSize: 13,
    },
    filterInput: {
      borderWidth: 1.2,
      borderColor: colors.inactiveBar,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      color: colors.primaryText,
      backgroundColor: colors.cardBg || colors.surface,
    },
    quickActionsRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 12,
      width: "100%",
      paddingHorizontal: 16,
    },
    quickActionButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      backgroundColor: colors.cardBg || colors.surface,
    },
    quickActionText: {
      color: colors.primaryText,
      fontWeight: "700",
      fontSize: 13,
    },
    listItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginHorizontal: 16,
      marginVertical: 8,
      backgroundColor: colors.cardBg || colors.surface,
      borderRadius: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 6,
      borderWidth: 0,
    },
    listItemActive: {
      borderColor: colors.accent,
      shadowOpacity: 0.14,
      backgroundColor: colors.cardBg || colors.surface,
    },
    thumbWrap: {
      width: 44,
      height: 44,
      marginRight: 12,
      position: "relative",
    },
    thumb: {
      width: 44,
      height: 44,
      borderRadius: 6,
      backgroundColor: colors.inactiveBar,
    },
    playingPill: {
      position: "absolute",
      right: -4,
      bottom: -4,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.accent,
      borderWidth: 2,
      borderColor: colors.background,
    },
    trackInfo: {
      flex: 1,
      justifyContent: "center",
    },
    trackTitle: {
      color: colors.primaryText,
      fontSize: 14,
      fontWeight: "700",
      marginBottom: 2,
      letterSpacing: -0.2,
    },
    trackArtist: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "500",
    },
    trackAlbum: {
      color: colors.secondaryText,
      fontSize: 11,
      marginTop: 2,
    },
    duration: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "600",
      marginRight: 12,
      minWidth: 36,
      textAlign: "right",
    },
    dotMenu: {
      padding: 8,
      borderRadius: 8,
      marginLeft: 8,
    },
    searchMetaWrap: {
      marginLeft: 8,
      minWidth: 42,
      alignItems: "flex-end",
      justifyContent: "center",
    },
    searchMetaText: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "700",
    },
    footerActionContainer: {
      position: "absolute",
      right: 16,
      bottom: 130,
      paddingHorizontal: 0,
      paddingVertical: 0,
      zIndex: 30,
      alignItems: 'flex-end',
      width: 56,
    },
    addTrackButton: {
      backgroundColor: colors.accent,
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.28,
      shadowRadius: 12,
      elevation: 6,
    },
    content: {
      paddingBottom: 124,
    },
    emptyListContent: {
      flexGrow: 1,
      paddingBottom: 24,
    },
    emptyStateCard: {
      marginHorizontal: 16,
      marginTop: 20,
      paddingVertical: 28,
      paddingHorizontal: 18,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      backgroundColor: colors.cardBg || colors.surface,
      alignItems: "center",
    },
    emptyStateTitle: {
      color: colors.primaryText,
      fontSize: 16,
      marginTop: 12,
    },
    emptyStateText: {
      color: colors.secondaryText,
      fontSize: 13,
      marginTop: 6,
      textAlign: "center",
    },
    addTrackButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 15,
      letterSpacing: 0.2,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: colors.background,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 30,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
    actionSheet: {
      backgroundColor: colors.background,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 24,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
    modalHeader: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.primaryText,
      marginBottom: 20,
      letterSpacing: -0.3,
    },
    actionSheetButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      backgroundColor: colors.cardBg || colors.surface,
      marginBottom: 10,
    },
    actionSheetButtonText: {
      color: colors.primaryText,
      fontSize: 15,
      fontWeight: "600",
    },
    actionSheetClose: {
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      backgroundColor: colors.cardBg || colors.surface,
      marginTop: 6,
    },
    actionSheetCloseText: {
      color: colors.secondaryText,
      fontSize: 14,
    },
    input: {
      borderWidth: 1.5,
      borderColor: colors.inactiveBar,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 12,
      color: colors.primaryText,
      marginBottom: 14,
      fontSize: 16,
      fontWeight: "500",
      backgroundColor: colors.cardBg || colors.surface,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
      marginTop: 20,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: colors.inactiveBar,
    },
    cancelButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
    },
    cancelButtonText: {
      color: colors.secondaryText,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.1,
    },
    saveButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.1,
    },
    sortOption: {
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
      marginBottom: 10,
      backgroundColor: colors.cardBg || colors.surface,
    },
    sortOptionText: {
      color: colors.primaryText,
      fontSize: 16,
      fontWeight: "600",
    },
    snackbar: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 92,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: colors.primaryText,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 10,
      elevation: 6,
    },
    snackbarText: {
      color: colors.background,
      fontSize: 13,
      fontWeight: "700",
      textAlign: "center",
    },
  });
