export const API_BASE_URL =
  "https://musicapp-production-bcd8.up.railway.app/api";
export const AUTH_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3MjMxMTg3LCJpYXQiOjE3NzcyMjc1ODcsImp0aSI6ImRiM2NmNTVhYjY3YzQ5NWE5ODYyMWEzZDU3Zjc0MWMxIiwidXNlcl9pZCI6IjIxIn0.fs5hvUcnroDv7FozU5f2S1HJ774jqsR-XjRsHfDAC6Q";
