import { Dimensions, StyleSheet } from "react-native";
import { ThemeColors } from "../../providers/ThemeProvider";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const makePlaylistsStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 20,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      borderBottomWidth: 1,
      borderBottomColor: colors.inactiveBar,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: "700",
      color: colors.primaryText,
      letterSpacing: -0.5,
      marginLeft: 12,
    },
    headerSpacer: {
      width: 32,
    },
    content: {
      paddingBottom: 120,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingBottom: 60,
    },
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
      paddingBottom: 60,
    },
    errorText: {
      color: colors.destructive || "#D14343",
      textAlign: "center",
      marginBottom: 20,
      fontSize: 16,
      fontWeight: "600",
      lineHeight: 22,
    },
    retryButton: {
      backgroundColor: colors.accent,
      borderRadius: 12,
      paddingHorizontal: 28,
      paddingVertical: 12,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    retryText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.2,
    },
    hero: {
      paddingHorizontal: 20,
      paddingVertical: 20,
    },
    heroTitle: {
      fontSize: 32,
      fontWeight: "800",
      color: colors.primaryText,
      marginBottom: 8,
      letterSpacing: -0.5,
    },
    heroSubtitle: {
      fontSize: 14,
      color: colors.secondaryText,
      lineHeight: 20,
      fontWeight: "500",
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.primaryText,
      marginBottom: 14,
      letterSpacing: -0.3,
    },
    sectionDivider: {
      height: 1,
      backgroundColor: colors.inactiveBar,
      marginTop: 2,
    },
    playlistsList: {
      paddingHorizontal: 0,
    },
    playlistCard: {
      width: 200,
      marginRight: 14,
      marginBottom: 30,
      shadowColor: "#000",
      shadowOpacity: 0.16,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
    },
    playlistArt: {
      width: "100%",
      height: 200,
      borderRadius: 14,
      overflow: "hidden",
      backgroundColor: colors.inactiveBar,
    },
    playlistImage: {
      width: "100%",
      height: "100%",
    },
    playlistOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(9, 17, 39, 0.18)",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingTop: 24,
      paddingHorizontal: 14,
      paddingBottom: 14,
    },
    playlistTrackCount: {
      color: "#fff",
      fontSize: 12,
      marginTop: 4,
      fontWeight: "600",
    },
    playlistTitle: {
      fontSize: 16,
      color: colors.primaryText,
      marginTop: 10,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    playlistDescription: {
      fontSize: 12,
      color: colors.secondaryText,
      marginTop: 4,
      fontWeight: "500",
    },
    tracksHeader: {
      paddingHorizontal: 20,
      marginTop: 24,
      marginBottom: 12,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    tracksHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    tracksHeaderIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    playAllButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    playAllText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 12,
      letterSpacing: 0.2,
    },
    tracksList: {
      paddingHorizontal: 20,
      paddingBottom: 24,
    },
    trackItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.cardBg || colors.surface,
      borderRadius: 14,
      marginBottom: 12,
      overflow: "hidden",
      paddingVertical: 10,
      paddingHorizontal: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.inactiveBar,
    },
    trackImage: {
      width: 56,
      height: 56,
      borderRadius: 10,
      marginRight: 12,
      backgroundColor: colors.inactiveBar,
    },
    trackInfo: {
      flex: 1,
      justifyContent: "center",
    },
    trackTitle: {
      fontSize: 14,
      color: colors.primaryText,
      marginBottom: 4,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    trackArtist: {
      fontSize: 12,
      color: colors.secondaryText,
      fontWeight: "500",
    },
    trackDuration: {
      fontSize: 12,
      color: colors.secondaryText,
      marginRight: 12,
      minWidth: 30,
      textAlign: "right",
      fontWeight: "600",
    },
    menuButton: {
      padding: 8,
      marginRight: -8,
      borderRadius: 8,
    },
    playButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
      paddingBottom: 60,
    },
    emptyStateIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    emptyStateTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.primaryText,
      marginBottom: 8,
      letterSpacing: -0.3,
      textAlign: "center",
    },
    emptyStateSubtitle: {
      fontSize: 14,
      color: colors.secondaryText,
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 24,
      fontWeight: "500",
    },
  });
